# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Selenium Java Web Automation CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Setup Java and other build tools
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      # Cache Maven dependencies and other build-related files
      - name: Cache build dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
            # Add other directories that you want to cache here
          key: ${{ runner.os }}-build-${{ hashFiles('pom.xml') }}

      - uses: browser-actions/setup-chrome@latest
      - run: chrome --version

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v3

      # Setup Java and other test-related tools
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      # Restore cached build dependencies
      - name: Restore cached build dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
            # Add other directories that you cached in the "build" stage
          key: ${{ runner.os }}-build-${{ hashFiles('pom.xml') }}

      - name: Running Regression Test Suite
        run: mvn clean test -Pheadless-chrome,qa
