# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Selenium Java Web Automation CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setting up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Setting up Chrome
      - uses: browser-actions/setup-chrome@latest
      - run: chrome --version
      - name: Running Regression Test Suite
        run: mvn clean test -Pheadless-chrome,qa
