# GitHub Workflow to build a Maven project & run the Selenium tests using the Chrome browser.
# Tools & technologies used for the automation project: TestNG, Selenium, Maven, and Java.
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Selenium Java Web Automation CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Setup Java
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      # Setup Maven
      - name: Set up Maven
        run: |
          wget -q https://archive.apache.org/dist/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz
          tar -xzf apache-maven-3.6.3-bin.tar.gz
          export PATH=$(pwd)/apache-maven-3.6.3/bin:$PATH

      # Setup Chrome Browser
      - name: Set up Chrome
        uses: browser-actions/setup-chrome@latest
        with:
          version: 'latest'

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v3

      # Check Build Environment
      - name: Check build environment
        run: |
          echo "Java version:"
          java -version

          echo "Maven version:"
          mvn -version

          echo "Chrome version:"
          google-chrome --version

      - name: Running Regression Test Suite
        run: mvn clean test -Pheadless-chrome,qa

      # Archive the "reports" folder
      - name: Archive test reports
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: reports
